# Generated by Django 3.2.16 on 2023-01-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../ball-flying_xiyzfz', upload_to='images/'),
        ),
    ]
