# Generated by Django 3.2.16 on 2023-01-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='support',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
