# Generated by Django 3.2.16 on 2023-01-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic',
            field=models.CharField(choices=[('General', 'General'), ('Players', 'Players'), ('Teams', 'Teams'), ('Transfers', 'Transfers'), ('Fixtures', 'Fixtures'), ('Results', 'Results')], max_length=20),
        ),
    ]
