# Generated by Django 3.2.16 on 2023-01-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topics_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic',
            field=models.CharField(max_length=30),
        ),
    ]
