# Generated by Django 3.2.16 on 2023-01-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
